package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.logging.Logger;


public class GUIstudente extends JFrame {
    private JPanel mainPanel;
    private JLabel messaggio;
    private JButton visualizzaorario;
    private JButton indietro;
    private static final Logger LOGGER = Logger.getLogger(GUIstudente.class.getName());

    public GUIstudente(String nomeStudente) {
        $$$setupUI$$$();
        setTitle("Area Riservata Studente");
        setContentPane(mainPanel);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(500, 400);
        setLocationRelativeTo(null);
        messaggio.setText("Benvenuto nella tua area riservata, " + nomeStudente + "!");
    }

    public void addVisualizzaOrarioListener(ActionListener listener) {
        if (visualizzaorario != null) {
            visualizzaorario.addActionListener(listener);
        } else {
            LOGGER.warning("Errore: visualizzaorario è null!");
        }
    }

    public void addIndietroListener(ActionListener listener) {
        if (indietro != null) {
            indietro.addActionListener(listener);
        } else {
            LOGGER.warning("Errore: Indietro è null nel codice dello Studente!");
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */@SuppressWarnings("java:S100")
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        messaggio = new JLabel();
        messaggio.setText("Benvenuto nella schermata studente");
        mainPanel.add(messaggio, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        visualizzaorario = new JButton();
        visualizzaorario.setText("Visualizza orario");
        mainPanel.add(visualizzaorario, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        indietro = new JButton();
        indietro.setText("Indietro");
        mainPanel.add(indietro, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */@SuppressWarnings("java:S100")
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}