package gui;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*; // Per JDialog, JPanel, JButton, JComboBox
import java.awt.*;    // Per Frame
import java.awt.event.ActionListener;

public class DialogVincoli extends JDialog {
    private JPanel contentPane;
    private JComboBox<String> giornoComboBox;
    private JComboBox<String> oraInizioComboBox;
    private JComboBox<String> oraFineComboBox;
    private JButton btnSalva;
    private JButton btnAnnulla;

    public DialogVincoli(Frame parent) {
        super(parent, "Inserisci Vincolo", true);
        setContentPane(contentPane);
        pack();
        setLocationRelativeTo(parent);
    }

    // Dentro DialogVincoli.java
    public JComboBox<String> getGiornoComboBox() { return giornoComboBox; }
    public String getOraInizioInput() { return oraInizioComboBox.getSelectedItem().toString(); }
    public String getOraFineInput() { return oraFineComboBox.getSelectedItem().toString(); }

    public void addSalvaListener(ActionListener listener) {
        btnSalva.addActionListener(listener);
    }

    public void addAnnullaListener(ActionListener listener) {
        btnAnnulla.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        giornoComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Lunedì");
        defaultComboBoxModel1.addElement("Martedì");
        defaultComboBoxModel1.addElement("Mercoledì");
        defaultComboBoxModel1.addElement("Giovedì");
        defaultComboBoxModel1.addElement("Venerdì");
        giornoComboBox.setModel(defaultComboBoxModel1);
        contentPane.add(giornoComboBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        oraInizioComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("8:00");
        defaultComboBoxModel2.addElement("9:00");
        defaultComboBoxModel2.addElement("10:00");
        defaultComboBoxModel2.addElement("11:00");
        defaultComboBoxModel2.addElement("12:00");
        defaultComboBoxModel2.addElement("13:00");
        defaultComboBoxModel2.addElement("14:00");
        defaultComboBoxModel2.addElement("15:00");
        defaultComboBoxModel2.addElement("16:00");
        defaultComboBoxModel2.addElement("17:00");
        defaultComboBoxModel2.addElement("18:00");
        oraInizioComboBox.setModel(defaultComboBoxModel2);
        contentPane.add(oraInizioComboBox, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        oraFineComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
        defaultComboBoxModel3.addElement("9:00");
        defaultComboBoxModel3.addElement("10:00");
        defaultComboBoxModel3.addElement("11:00");
        defaultComboBoxModel3.addElement("12:00");
        defaultComboBoxModel3.addElement("13:00");
        defaultComboBoxModel3.addElement("14:00");
        defaultComboBoxModel3.addElement("15:00");
        defaultComboBoxModel3.addElement("16:00");
        defaultComboBoxModel3.addElement("17:00");
        defaultComboBoxModel3.addElement("18:00");
        defaultComboBoxModel3.addElement("19:00");
        oraFineComboBox.setModel(defaultComboBoxModel3);
        contentPane.add(oraFineComboBox, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnSalva = new JButton();
        btnSalva.setText("Salva");
        contentPane.add(btnSalva, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAnnulla = new JButton();
        btnAnnulla.setText("Annulla");
        contentPane.add(btnAnnulla, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}