package gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

public class GUIdocenteresponsabile extends JFrame {    // Finestra dedicata alle funzionalità del docente responsabile
    private JPanel mainPanel;            // Pannello radice collegato alla grafica del file .form
    private JButton VisualizzaRichieste;    // Bottone per aprire l'elenco delle richieste di spostamento in attesa
    private JButton Logout;            // Bottone di logout per uscire e tornare alla schermata principale
    private JLabel Titolo;            // Etichetta del titolo per mostrare il messaggio di benvenuto personalizzato

    public GUIdocenteresponsabile(String cognomeDocente) {    // Costruttore: riceve il cognome del responsabile che ha effettuato l'accesso
        setTitle("Area Docente Responsabile");    // Imposta la scritta sulla barra del titolo della finestra
        setContentPane(mainPanel);        // Associa il pannello principale del designer alla finestra
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);    // Termina l'applicazione del tutto alla chiusura della finestra con la x
        setSize(600, 450);            // Risoluzione iniziale della finestra (larghezza e altezza)
        setLocationRelativeTo(null);        // Fa apparire la finestra esattamente al centro dello schermo

        if (Titolo != null) {            // Controllo di sicurezza per evitare NullPointerException prima di modificare il testo
            Titolo.setText("Benvenuto Coordinatore, Prof. " + cognomeDocente);    // Imposta il testo di benvenuto con il cognome dinamico
        }
    }

    public void addVisualizzaRichiesteListener(ActionListener listener) {    // Passa il listener del controller al bottone per esaminare le richieste pendenti
        if (VisualizzaRichieste != null) {
            VisualizzaRichieste.addActionListener(listener);
        } else {
            System.out.println("Errore: Il bottone delle richieste del responsabile è null!");    // Messaggio di log utile in console per controllare se il name field nel .form è corretto
        }
    }

    public void addLogoutListener(ActionListener listener) {    // Passa il listener del controller al bottone di logout per gestire la disconnessione
        if (Logout != null) {
            Logout.addActionListener(listener);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        Titolo = new JLabel();
        Titolo.setHorizontalAlignment(10);
        Titolo.setText("Home responsabile");
        mainPanel.add(Titolo, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        VisualizzaRichieste = new JButton();
        VisualizzaRichieste.setText("Visualizza richieste spostamento lezioni");
        mainPanel.add(VisualizzaRichieste, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Logout = new JButton();
        Logout.setText("Logout");
        mainPanel.add(Logout, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}