package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.logging.Logger;

public class GUIdocenteresponsabile extends JFrame {    // Finestra dedicata alle funzionalità del docente responsabile
    private JPanel mainPanel;            // Pannello radice collegato alla grafica del file .form
    private JButton visualizzarichieste;    // Bottone per aprire l'elenco delle richieste di spostamento in attesa
    private JButton logout;            // Bottone di logout per uscire e tornare alla schermata principale
    private JLabel titolo;            // Etichetta del titolo per mostrare il messaggio di benvenuto personalizzato
    private static final Logger LOGGER = Logger.getLogger(GUIdocenteresponsabile.class.getName());

    public GUIdocenteresponsabile(String cognomeDocente) {    // Costruttore: riceve il cognome del responsabile che ha effettuato l'accesso
        $$$setupUI$$$();
        setTitle("Area Docente Responsabile");    // Imposta la scritta sulla barra del titolo della finestra
        setContentPane(mainPanel);        // Associa il pannello principale del designer alla finestra
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);    // Termina l'applicazione del tutto alla chiusura della finestra con la x
        setSize(600, 450);            // Risoluzione iniziale della finestra (larghezza e altezza)
        setLocationRelativeTo(null);        // Fa apparire la finestra esattamente al centro dello schermo

        if (titolo != null) {            // Controllo di sicurezza per evitare NullPointerException prima di modificare il testo
            titolo.setText("Benvenuto Coordinatore, Prof. " + cognomeDocente);    // Imposta il testo di benvenuto con il cognome dinamico
        }
    }

    public void addVisualizzaRichiesteListener(ActionListener listener) {    // Passa il listener del controller al bottone per esaminare le richieste pendenti
        if (visualizzarichieste != null) {
            visualizzarichieste.addActionListener(listener);
        } else {
            LOGGER.warning("Errore: Il bottone delle richieste del responsabile è null!");
        }
    }

    public void addLogoutListener(ActionListener listener) {    // Passa il listener del controller al bottone di logout per gestire la disconnessione
        if (logout != null) {
            logout.addActionListener(listener);
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */@SuppressWarnings("java:S100")
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        titolo = new JLabel();
        titolo.setHorizontalAlignment(10);
        titolo.setText("Home responsabile");
        mainPanel.add(titolo, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        visualizzarichieste = new JButton();
        visualizzarichieste.setText("Visualizza richieste spostamento lezioni");
        mainPanel.add(visualizzarichieste, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logout = new JButton();
        logout.setText("Logout");
        mainPanel.add(logout, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */@SuppressWarnings("java:S100")
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}