package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.logging.Logger;

/**
 * Finestra Swing che rappresenta l'area riservata del docente.
 * Permette al docente di visualizzare il proprio orario, aprire il pannello
 * per richiedere lo spostamento di una lezione ed effettuare il logout.
 */
public class GUIdocente extends JFrame {
    private static final long serialVersionUID = 1L;
    private JPanel mainPanel;
    private JLabel messaggioDocente;
    private JButton visualizzaOrarioDocente;
    private JButton richiestaSpostamentoLezione;
    private JButton logout;
    private CardLayout cardLayout;
    private JPanel pannelloContenitore;
    private static final Logger LOGGER = Logger.getLogger(GUIdocente.class.getName());

    /**
     * Crea la finestra dell'area riservata del docente.
     * Inizializza i componenti grafici, configura il contenitore a schede
     * e mostra un messaggio di benvenuto personalizzato.
     *
     * @param cognomeDocente cognome del docente autenticato
     */
    public GUIdocente(String cognomeDocente) {
        $$$setupUI$$$();
        setTitle("Area Riservata Docente");
        cardLayout = new CardLayout();
        pannelloContenitore = new JPanel(cardLayout);
        pannelloContenitore.add(mainPanel, "DASHBOARD_INIZIALE");
        setContentPane(pannelloContenitore);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(500, 400);
        setLocationRelativeTo(null);
        inizializzaDati(cognomeDocente);
    }

    /**
     * Imposta il messaggio di benvenuto del docente.
     *
     * @param cognomeDocente cognome del docente autenticato
     */
    private void inizializzaDati(String cognomeDocente) {
        if (messaggioDocente != null) {
            messaggioDocente.setText("Benvenuto nel portale docenti, Prof. " + cognomeDocente + "!");
        } else {
            LOGGER.warning("Errore: MessaggioDocente è nullo! Controlla il file .form");
        }
    }

    /**
     * Mostra il pannello dedicato alla richiesta di spostamento lezione.
     * Il nuovo pannello viene aggiunto al contenitore principale e visualizzato
     * tramite {@link CardLayout}.
     *
     * @param nuovoPannello pannello da mostrare per la richiesta di spostamento
     */
    public void mostraPannelloSpostamento(JPanel nuovoPannello) {
        try {
            pannelloContenitore.remove(nuovoPannello);
        } catch (IllegalArgumentException e) {
            // Il pannello potrebbe non essere ancora presente nel contenitore.
        }

        pannelloContenitore.add(nuovoPannello, "FORM_SPOSTAMENTO");
        cardLayout.show(pannelloContenitore, "FORM_SPOSTAMENTO");
    }

    /**
     * Collega un listener al pulsante per visualizzare l'orario del docente.
     * Il listener viene fornito dal controller.
     *
     * @param listener listener da associare al pulsante "Visualizza orario"
     */
    public void addVisualizzaOrarioDocenteListener(ActionListener listener) {
        if (visualizzaOrarioDocente != null) {
            visualizzaOrarioDocente.addActionListener(listener);
        }
    }

    /**
     * Collega un listener al pulsante per richiedere lo spostamento di una lezione.
     * Il listener viene fornito dal controller.
     *
     * @param listener listener da associare al pulsante "Richiesta spostamento lezione"
     */
    public void addRichiestaSpostamentoLezioneListener(ActionListener listener) {
        if (richiestaSpostamentoLezione != null) {
            richiestaSpostamentoLezione.addActionListener(listener);
        }
    }

    /**
     * Collega un listener al pulsante di logout.
     * Il listener viene fornito dal controller.
     *
     * @param listener listener da associare al pulsante "Logout"
     */
    public void addLogoutListener(ActionListener listener) {
        if (logout != null) {
            logout.addActionListener(listener);
        }
    }

    /**
     * Torna alla schermata iniziale dell'area docente.
     */
    public void mostraPannelloIniziale() {
        cardLayout.show(pannelloContenitore, "DASHBOARD_INIZIALE");
    }

    /*
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    @SuppressWarnings("java:S100")
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        visualizzaOrarioDocente = new JButton();
        visualizzaOrarioDocente.setText("Visualizza orario");
        mainPanel.add(visualizzaOrarioDocente, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        richiestaSpostamentoLezione = new JButton();
        richiestaSpostamentoLezione.setText("Richiesta spostamento lezione");
        mainPanel.add(richiestaSpostamentoLezione, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        messaggioDocente = new JLabel();
        messaggioDocente.setText("Schermata docente");
        mainPanel.add(messaggioDocente, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logout = new JButton();
        logout.setText("Logout");
        mainPanel.add(logout, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /*
     * @noinspection ALL
     */
    @SuppressWarnings("java:S100")
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}