package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.logging.Logger;

public class GUIdocenteresponsabile extends JFrame {
    private JPanel mainPanel;
    private JButton visualizzarichieste;
    private JButton logout;
    private JLabel titolo;
    private static final Logger LOGGER = Logger.getLogger(GUIdocenteresponsabile.class.getName());

    public GUIdocenteresponsabile(String cognomeDocente) {
        $$$setupUI$$$();
        setTitle("Area Docente Responsabile");
        setContentPane(mainPanel);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(600, 450);
        setLocationRelativeTo(null);
        if (titolo != null) {
            titolo.setText("Benvenuto Coordinatore, Prof. " + cognomeDocente);
        }
    }

    public void addVisualizzaRichiesteListener(ActionListener listener) {
        if (visualizzarichieste != null) {
            visualizzarichieste.addActionListener(listener);
        } else {
            LOGGER.warning("Errore: Il bottone delle richieste del responsabile è null!");
        }
    }

    public void addLogoutListener(ActionListener listener) {
        if (logout != null) {
            logout.addActionListener(listener);
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */@SuppressWarnings("java:S100")
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        titolo = new JLabel();
        titolo.setHorizontalAlignment(10);
        titolo.setText("Home responsabile");
        mainPanel.add(titolo, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        visualizzarichieste = new JButton();
        visualizzarichieste.setText("Visualizza richieste spostamento lezioni");
        mainPanel.add(visualizzarichieste, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logout = new JButton();
        logout.setText("Logout");
        mainPanel.add(logout, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */@SuppressWarnings("java:S100")
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}