package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * Finestra principale dell'applicazione.
 * Permette all'utente di scegliere il tipo di accesso, inserire le credenziali
 * e passare alla schermata di login per studente, docente o docente responsabile.
 */
public class GUIhome extends JFrame {
    private JPanel panel1;
    private JPanel mainPanel;

    @SuppressWarnings("java:S1450")
    private JPanel panelBottoni;

    private JPanel panelLogin;

    @SuppressWarnings("java:S1450")
    private JLabel home;

    @SuppressWarnings("java:S1450")
    private JButton docente;

    private JButton studente;
    private JTextField email;
    private JTextField password;
    private JButton accedi;
    private JButton indietro;
    private JButton docenteresponsabile;
    private JTextField codiceresponsabile;

    /**
     * Crea la finestra home dell'applicazione.
     * Inizializza i componenti grafici, imposta il pannello principale
     * e configura le proprietà di base della finestra.
     */
    public GUIhome() {
        $$$setupUI$$$();
        setTitle("Portale Universitario");
        setContentPane(panel1);
        mainPanel.add(panelLogin, "SCHERMATA_LOGIN");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(450, 350);
        setLocationRelativeTo(null);
    }

    /**
     * Mostra una specifica schermata del pannello principale tramite {@link CardLayout}.
     *
     * @param nomeCard nome della schermata da visualizzare
     */
    public void mostraSchermata(String nomeCard) {
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, nomeCard);
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    /**
     * Collega un listener al pulsante di login docente.
     *
     * @param l listener da associare al pulsante docente
     */
    public void addDocenteListener(ActionListener l) {
        docente.addActionListener(l);
    }

    /**
     * Collega un listener al pulsante di login studente.
     *
     * @param l listener da associare al pulsante studente
     */
    public void addStudenteListener(ActionListener l) {
        studente.addActionListener(l);
    }

    /**
     * Collega un listener al pulsante di accesso.
     *
     * @param listener listener da associare al pulsante "Accedi"
     */
    public void addAccediListener(ActionListener listener) {
        accedi.addActionListener(listener);
    }

    /**
     * Collega un listener al pulsante per tornare alla schermata precedente.
     *
     * @param listener listener da associare al pulsante "Indietro"
     */
    public void addIndietroListener(ActionListener listener) {
        indietro.addActionListener(listener);
    }

    /**
     * Collega un listener al pulsante di login del docente responsabile.
     *
     * @param listener listener da associare al pulsante docente responsabile
     */
    public void addDocenteResponsabileListener(ActionListener listener) {
        docenteresponsabile.addActionListener(listener);
    }

    /**
     * Restituisce il codice inserito per l'accesso come docente responsabile.
     *
     * @return codice inserito, senza spazi iniziali o finali
     */
    public String getCodiceInput() {
        return codiceresponsabile.getText().trim();
    }

    /**
     * Imposta la visibilità del campo codice responsabile.
     * Il campo viene mostrato solo quando l'utente sceglie l'accesso
     * come docente responsabile.
     *
     * @param visibile true per mostrare il campo, false per nasconderlo
     */
    public void impostaVisibilitaCodice(boolean visibile) {
        codiceresponsabile.setVisible(visibile);
        codiceresponsabile.revalidate();
        codiceresponsabile.repaint();
    }

    /**
     * Restituisce l'email inserita nella schermata di login.
     *
     * @return email inserita dall'utente
     */
    public String getEmailInput() {
        return email.getText();
    }

    /**
     * Restituisce la password inserita nella schermata di login.
     *
     * @return password inserita dall'utente
     */
    public String getPasswordInput() {
        return password.getText();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new CardLayout(0, 0));
        panel1.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        mainPanel = new JPanel();
        mainPanel.setLayout(new CardLayout(0, 0));
        panel1.add(mainPanel, "Card1");
        panelBottoni = new JPanel();
        panelBottoni.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panelBottoni, "SchermataBottoni");
        docente = new JButton();
        docente.setText("login docente");
        panelBottoni.add(docente, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        studente = new JButton();
        studente.setText("login studente");
        panelBottoni.add(studente, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        docenteresponsabile = new JButton();
        docenteresponsabile.setText("login docente responsabile");
        panelBottoni.add(docenteresponsabile, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        home = new JLabel();
        home.setText("HOME");
        panelBottoni.add(home, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelLogin = new JPanel();
        panelLogin.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panelLogin, "SchermataLogin");
        email = new JTextField();
        email.setText("Email");
        panelLogin.add(email, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), new Dimension(200, 30), 0, false));
        password = new JTextField();
        password.setText("Password");
        panelLogin.add(password, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), new Dimension(200, 30), 0, false));
        indietro = new JButton();
        indietro.setText("Indietro");
        panelLogin.add(indietro, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        codiceresponsabile = new JTextField();
        codiceresponsabile.setText("Codice");
        panelLogin.add(codiceresponsabile, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), new Dimension(200, 30), 0, false));
        accedi = new JButton();
        accedi.setText("Accedi");
        panelLogin.add(accedi, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}