package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionListener;

public class GUIhome extends JFrame { // Finestra principale di ingresso (punto di partenza)
    private JPanel panel1;            // Pannello radice che contiene l'intera interfaccia
    private JPanel mainPanel;            // Pannello centrale configurato con CardLayout per switchare le schermate
    @SuppressWarnings("java:S1450")
    private JPanel panelBottoni;        // Pannello della schermata iniziale con la scelta del ruolo
    private JPanel panelLogin;            // Pannello con i campi di testo per l'autenticazione
    private JLabel home;            // Etichetta del titolo principale del portale

    @SuppressWarnings("java:S1450")
    private JButton docente;            // Bottone per selezionare l'accesso come docente normale
    private JButton studente;            // Bottone per selezionare l'accesso come studente
    private JTextField email;            // Campo di testo per l'inserimento dell'email utente
    private JTextField password;        // Campo di testo per l'inserimento della password
    private JButton accedi;            // Bottone per confermare l'invio dei dati di login
    private JButton indietro;            // Bottone per annullare il login e tornare alla scelta del ruolo
    private JButton docenteresponsabile;    // Bottone per selezionare l'accesso come coordinatore/responsabile
    private JTextField codiceresponsabile;    // Campo di testo aggiuntivo per il codice di sicurezza del responsabile

    public GUIhome() {                // Costruttore: configura le proprietà di base della finestra iniziale
        $$$setupUI$$$();
        setTitle("Portale Universitario");    // Imposta il titolo sulla barra superiore della finestra
        setContentPane(panel1); // Associa il pannello principale alla finestra
        mainPanel.add(panelLogin, "SCHERMATA_LOGIN");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(450, 350);            // Imposta le dimensioni della finestra di login
        setLocationRelativeTo(null);        // Centra la finestra sullo schermo dell'utente
    }

    public void mostraSchermata(String nomeCard) {    // Metodo per cambiare schermata
        CardLayout cl = (CardLayout) mainPanel.getLayout();    // Recupera il gestore CardLayout dal pannello centrale
        cl.show(mainPanel, nomeCard);        // Mostra la schermata corrispondente al nome passato come parametro
        mainPanel.revalidate();            // Ricalcola il layout per evitare glitch grafici dopo lo switch
        mainPanel.repaint();            // Rinfresca visivamente i componenti grafici del pannello
    }

    public void addDocenteListener(ActionListener l) {    // Aggancia il listener del controller al bottone docente
        docente.addActionListener(l);
    }

    public void addStudenteListener(ActionListener l) {    // Aggancia il listener del controller al bottone Studente
        studente.addActionListener(l);
    }

    public void addAccediListener(ActionListener listener) {    // Aggancia il listener al bottone Accedi per verificare le credenziali
        accedi.addActionListener(listener);
    }

    public void addIndietroListener(ActionListener listener) {    // Aggancia il listener al bottone Indietro per tornare alla home
        indietro.addActionListener(listener);
    }

    public void addDocenteResponsabileListener(ActionListener listener) {    // Aggancia il listener al bottone del docente Responsabile
        docenteresponsabile.addActionListener(listener);
    }

    public String getCodiceInput() {        // Restituisce il codice inserito dal responsabile eliminando spazi vuoti
        return codiceresponsabile.getText().trim();
    }

    public void impostaVisibilitaCodice(boolean visibile) {    // Mostra o nasconde il campo codice a seconda del ruolo selezionato
        codiceresponsabile.setVisible(visibile);    // Cambia lo stato di visibilità del componente
        codiceresponsabile.revalidate();    // Aggiorna la struttura del layout dopo il cambio di visibilità
        codiceresponsabile.repaint();        // Ridisegna il componente a schermo
    }

    public String getEmailInput() {        // Restituisce il testo digitato nel campo Email
        return email.getText();
    }

    public String getPasswordInput() {        // Restituisce il testo digitato nel campo Password
        return password.getText();
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new CardLayout(0, 0));
        panel1.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        mainPanel = new JPanel();
        mainPanel.setLayout(new CardLayout(0, 0));
        panel1.add(mainPanel, "Card1");
        panelBottoni = new JPanel();
        panelBottoni.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panelBottoni, "SchermataBottoni");
        docente = new JButton();
        docente.setText("login docente");
        panelBottoni.add(docente, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        studente = new JButton();
        studente.setText("login studente");
        panelBottoni.add(studente, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        home = new JLabel();
        home.setText("HOME");
        panelBottoni.add(home, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        docenteresponsabile = new JButton();
        docenteresponsabile.setText("login docente responsabile");
        panelBottoni.add(docenteresponsabile, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelLogin = new JPanel();
        panelLogin.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panelLogin, "SchermataLogin");
        email = new JTextField();
        email.setText("Email");
        panelLogin.add(email, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), new Dimension(200, 30), 0, false));
        accedi = new JButton();
        accedi.setText("Accedi");
        panelLogin.add(accedi, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        password = new JTextField();
        password.setText("Password");
        panelLogin.add(password, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), new Dimension(200, 30), 0, false));
        indietro = new JButton();
        indietro.setText("Indietro");
        panelLogin.add(indietro, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        codiceresponsabile = new JTextField();
        codiceresponsabile.setText("Codice");
        panelLogin.add(codiceresponsabile, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), new Dimension(200, 30), 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}