package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

public class GUIstudente extends JFrame {    // Finestra principale per la dashboard dell'utente studente
    private JPanel mainPanel;            // Pannello radice collegato alla grafica del file .form
    private JLabel messaggio;            // Etichetta di testo per salutare lo studente loggato
    private JButton visualizzaorario;        // Bottone per accedere alla visualizzazione dell'orario lezioni
    private JButton indietro;            // Bottone per disconnettersi e ritornare alla pagina di login

    public GUIstudente(String nomeStudente) {    // Costruttore: riceve il nome dello studente per personalizzare la view
        $$$setupUI$$$();
        setTitle("Area Riservata Studente");    // Imposta la scritta sulla barra in alto della finestra
        setContentPane(mainPanel);        // Associa il pannello del designer come contenuto della finestra
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);    // Spegne il processo java alla chiusura della finestra con la x
        setSize(500, 400);            // Definisce la risoluzione in pixel della schermata dello studente
        setLocationRelativeTo(null);        // Fa comparire la finestra esattamente al centro dello schermo

        messaggio.setText("Benvenuto nella tua area riservata, " + nomeStudente + "!");    // Scrive il testo di benvenuto dinamico
    }

    public void addVisualizzaOrarioListener(ActionListener listener) {    // Collega l'azione del controller al tasto dell'orario
        if (visualizzaorario != null) {
            visualizzaorario.addActionListener(listener);
        } else {
            System.out.println("Errore: VisualizzaOrario è null!");    // Log di avviso se il bottone non è configurato nel .form
        }
    }

    public void addIndietroListener(ActionListener listener) {    // Collega l'azione del controller al tasto indietro per il logout
        if (indietro != null) {
            indietro.addActionListener(listener);
        } else {
            System.out.println("Errore: Indietro è null nel codice dello Studente!");    // Log di controllo per verificare il name field nel designer
        }
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    @SuppressWarnings("java:S100")
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        messaggio = new JLabel();
        messaggio.setText("Benvenuto nella schermata studente");
        mainPanel.add(messaggio, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        visualizzaorario = new JButton();
        visualizzaorario.setText("Visualizza orario");
        mainPanel.add(visualizzaorario, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        indietro = new JButton();
        indietro.setText("Indietro");
        mainPanel.add(indietro, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    @SuppressWarnings("java:S100")
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}